### PR TITLE
[fix/github409] Fixed Pivot table header with component name and groups

### LINKED ISSUE #409: Mild confusion between input traML column names and output PivotTable column names
**Describe the bug**
The first two columns in the PivotTable are "component_group_name" and "component_name." I would expect the following correspondence between the PivotTable columns and the TraML columns:

| PivotTable column | expected to correspond to | TraML column |
| --- | --- | --- |
| component_group_name | | transition_group_id |
| component_name | | transition_name

However, the contents of the PivotTable columns are in fact reversed from my expectation, and the column correspondence is this:

| PivotTable column | actually corresponds to | TraML column |
| --- | --- | --- |
| component_group_name | | transition_name |
| component_name | | transition_group_name

I would consider this a bug since the columns are not as expected. Or perhaps I am misunderstanding the meaning of the output column names.

**To Reproduce**
1. Run SmartPeak and export a PivotTable
2. View columns from TraML and compare to PivotTable

**Expected behavior**
| PivotTable column | expected to correspond to | TraML column |
| --- | --- | --- |
| component_group_name | | transition_group_id |
| component_name | | transition_name

**Screenshots**
The following is the TraML for the example dataset LCMS_MRM_Unknowns:

image

And the following is the PivotTable exported from running the LCMS MRM workflow preset:

image

**data**
None to share

**Version information**
 - OS: Windows 10
 - Version 1.12.0

### PR DESCRIPTION
**Pull request by bertrandboudaud**
There is an inconsistency with the columns defined in  ``makeDataMatrixFromMetaValue``
```
    for (const auto& r: rows) {
      rows_out(row, 0) = r.component_name;
      rows_out(row, 1) = r.component_group_name;
      rows_out(row, 2) = r.meta_value_name;
      ++row;
    }
```

and the header of the pivot table in ``writeDataMatrixFromMetaValue``:
```
    std::vector<std::string> headers = {"component_group_name", "component_name", "meta_value"};
```

- added non regression test

### CODE REVIEW

File: src/tests/class_tests/smartpeak/source/SequenceParser_test.cpp [hunk 1]
```diff
@@ -331,19 +339,95 @@ TEST_F(SequenceParserFixture, makeDataMatrixFromMetaValue)
...
   EXPECT_EQ(rows_out.dimension(0), 1);
   EXPECT_EQ(rows_out.dimension(1), 3);
   EXPECT_STREQ(rows_out(0, 1).c_str(), "23dpg");
   EXPECT_NEAR(data_out(0, 0), 15.6053667, 1e-3);
+}
 
-  // write sequence to output
-  // const std::string pathname_output = SMARTPEAK_GET_TEST_DATA_PATH("output/SequenceParser_writeDataMatrixFromMetaValue.csv");
-  // SequenceParser::writeDataMatrixFromMetaValue(sequenceHandler, pathname_output);
+TEST_F(SequenceParserFixture, writeDataMatrixFromMetaValue)
```
Comment (dmccloskey) [inline src/tests/class_tests/smartpeak/source/SequenceParser_test.cpp:360]: Thanks for completing the test!

File: src/tests/class_tests/smartpeak/source/SequenceParser_test.cpp [hunk 2]
```diff
@@ -331,19 +339,95 @@ TEST_F(SequenceParserFixture, makeDataMatrixFromMetaValue)
   EXPECT_NEAR(data_out(0,0), 15.6053667, 1e-3);
   EXPECT_NEAR(data_out(rows_out.dimension(0)-1,columns_out.size()-1), 1.66744995, 1e-3);
 
-  SequenceParser::makeDataMatrixFromMetaValue(sequence_handler_, data_out, columns_out, rows_out, std::vector<std::string>({ "leftWidth" }), sample_types,
-    std::set<std::string>({ "170808_Jonathan_yeast_Sacc1_1x" }), std::set<std::string>({ "23dpg" }), std::set<std::string>({ "23dpg.23dpg_1.Light" }));
+  SequenceParser::makeDataMatrixFromMetaValue(sequence_handler_,
```
Comment (dmccloskey) [inline src/tests/class_tests/smartpeak/source/SequenceParser_test.cpp:342]: Nice modification.

**Review by dmccloskey — APPROVED** [review]
