### PR TITLE
Fix export of Pivot Table

### LINKED ISSUE #441: SmartPeakGUI - Saving PivotTable report produces generates a CSV that looks like FeatureDB
**Describe the bug**
When creating a PivotTable report through the Windows GUI, the generated CSV file looks like the FeatureDB report, and not like a PivotTable report. When running SmartPeak through the CLI, the PivotTable report looks the same as in previous versions.

**To Reproduce**
1. Open SmartPeak GUI
2. Load any dataset and run workflow
3. Actions > Report > Create Pivot Table
4. Open PivotTable.csv and see data

**Expected behavior**
PivotTable.csv should have the format same as before, with columns: component_name, component_group_name, meta_value, sample1, sample2, ...

**log**
 - Windows: [smartpeak_log_2021-10-15_16-30-48.log](https://github.com/AutoFlowResearch/SmartPeak/files/7356388/smartpeak_log_2021-10-15_16-30-48.log)

**data**
From the LCMS_MRM_Unknowns example dataset:
- [old_PivotTable.csv](https://github.com/AutoFlowResearch/SmartPeak/files/7356390/old_PivotTable.csv)
- Generated from v1.15.0 GUI [PivotTable.csv](https://github.com/AutoFlowResearch/SmartPeak/files/7356391/PivotTable.csv)

**Version information**
 - OS: Windows 10
 - Version 1.15.0

### PR DESCRIPTION
**Pull request by bertrandboudaud**
A regression has been introduced when doing the file selection for the Pivot Table and Table report.
This fixes it.

### CODE REVIEW

File: src/smartpeak/include/SmartPeak/ui/Report.h [hunk 1]
```diff
@@ -66,15 +66,20 @@ namespace SmartPeak
   protected:
     struct ReportFilePickerHandler : IFilePickerHandler
     {
-      ReportFilePickerHandler(const Report& report, const std::string title) :
-        report_(report), title_(title) { };
+      typedef  bool (*WriterMethod)(const SequenceHandler&,
```
Comment (dmccloskey) [inline src/smartpeak/include/SmartPeak/ui/Report.h:69]: Elegant

**Review by dmccloskey — APPROVED** [review]
