### PR TITLE
[fix/aut1001] Fixed handling of windows separators in CLI.

### LINKED ISSUE #396: Improper input filepath inference in SmartPeakCLI
**Describe the bug**
Providing a sequence.csv file will cause the SmartPeak CLI to improperly infer the location of parameters.csv and traml.csv as inside a subdirectory named "sequence.csv" instead of searching the parent directory of the sequence.csv file.

**To Reproduce**
Provide SmartPeak CLI with a sequence file, e.g. with the command `SmartPeakCLI.exe -l .\sequence.csv`. (Providing relative / absolute paths will both cause this bug to manifest)

**Expected behavior**
Expected SmartPeak to find `parameters.csv` and `traml.csv` in the parent directory as `sequence.csv`, instead of treating `sequence.csv` as the directory to search in.

**logs**
 - Windows: 
[smartpeak_log_2021-07-19.zip](https://github.com/AutoFlowResearch/SmartPeak/files/6844346/smartpeak_log_2021-07-19.zip)

**data**
N/A

**Version information**
 - OS: Windows 10 v1909
 - Version 1.11.0

**Additional context**
Would you consider adding separate options for specifying a path to the MZML directory and parameters.csv file, instead of implicitly assuming everything to be deposited in the same directory?

### PR DESCRIPTION
**Pull request by bertrandboudaud**

### CODE REVIEW

File: src/smartpeak/source/core/SequenceProcessor.cpp [hunk 1]
```diff
@@ -80,7 +81,7 @@ namespace SmartPeak
   bool CreateSequence::buildStaticFilenames(ApplicationHandler* application_handler)
   {
     Filenames& f = application_handler->static_filenames_;
-    application_handler->main_dir_ = application_handler->sequence_pathname_.substr(0, application_handler->sequence_pathname_.find_last_of('/'));
+    application_handler->main_dir_ = std::filesystem::path(application_handler->sequence_pathname_).remove_filename().generic_string();
```
Comment (dmccloskey) [inline src/smartpeak/source/core/SequenceProcessor.cpp:84]: Much better solution.

File: src/tests/class_tests/smartpeak/source/SequenceProcessor_test.cpp [hunk 2]
```diff
@@ -76,6 +76,31 @@ TEST(SequenceHandler, createSequence_onFilePicked)
   EXPECT_STREQ(injection0.getRawData().getQuantitationMethods()[0].getComponentName().c_str(), "arg-L.arg-L_1.Light");
 }
 
+#if (WIN32)
```
Comment (dmccloskey) [inline src/tests/class_tests/smartpeak/source/SequenceProcessor_test.cpp:79]: Thanks for adding this section to the test.

**Review by dmccloskey — APPROVED** [review]
Looks good.  Thanks for finding and solving so quickly.
